[package]
name = "doubletake"
version = "0.0.0-alpha.1"
license = "CC0-1.0"
edition = "2021"
authors = [ "Steven Roose <steven@roose.io>", "James Dorfman" ]
description = "A library and CLI tool for creating Bitcoin double spend prevention bonds on Liquid"


[dependencies]
bitcoin = { version = "0.30.1", features = [ "rand" ] }
elements = "0.23.0"
hex-conservative = "0.1.1"
